# Generated by Django 2.0.4 on 2018-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_user_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.IntegerField(default='0'),
        ),
    ]
